### ISSUE TITLE
Support for larger blur radius values

### ISSUE THREAD

**Issue by ribru17** [bouteillerAlan/blurredwallpaper#17]
### What is the problem this feature will solve?

Hello and thanks for the great plugin. One very tiny problem I have with it, though, is that I cannot get the blur radius high enough to match my other window blurs (KVantum Sweet theme) and I use inactive blur the blur the background behind other windows that I have that are transparent but do not support blur (Wezterm). The blur radii are slightly different so when I have Wezterm side-by-side with, say, Dolphin, the blurs don't quite match up as the KVantum blur radius is quite high. However I cannot raise the Active Blur radius above 100 px.

### What is the feature you are proposing to solve the problem?

It would be great if I could exceed 100 pixels for the active blur radius so I can finally match the blur radius provided by my other windows to keep it the same and looking nice and uniform. Thank you!

**Comment by bouteillerAlan** [comment]
Hi @ribru17 I made an update. I keep you in touch when the update land on the pling store :) 

Just for information :
- in my case, when I set the blur radius with a value higher than 145 my wallpaper blackout totally, so I have added an information message about that too
- and due to the limitation of the QT framework if the value of the blur radius exceeds 64 the blur quality may be reduced ([link to the QT documentation](https://doc.qt.io/qt-5/qml-qtgraphicaleffects-fastblur.html#radius-prop))

**Comment by bouteillerAlan** [comment]
The store is up to date :rocket:
